class Characters
  attr_reader :latin_braille,
              :braille_latin

  def initialize
    @latin_braille = Hash.new
      latin_braille["a"] = ["0.", "..", ".."]
      latin_braille["b"] = ["0.", "0.", ".."]
      latin_braille["c"] = ["00", "..", ".."]
      latin_braille["d"] = ["00", ".0", ".."]
      latin_braille["e"] = ["0.", ".0", ".."]
      latin_braille["f"] = ["00", "0.", ".."]
      latin_braille["g"] = ["00", "00", ".."]
      latin_braille["h"] = ["0.", "00", ".."]
      latin_braille["i"] = [".0", "0.", ".."]
      latin_braille["j"] = [".0", "00", ".."]
      latin_braille["k"] = ["0.", "..", "0."]
      latin_braille["l"] = ["0.", "0.", "0."]
      latin_braille["m"] = ["00", "..", "0."]
      latin_braille["n"] = ["00", ".0", "0."]
      latin_braille["o"] = ["0.", ".0", "0."]
      latin_braille["p"] = ["00", "0.", "0."]
      latin_braille["q"] = ["00", "00", "0."]
      latin_braille["r"] = ["0.", "00", "0."]
      latin_braille["s"] = [".0", "0.", "0."]
      latin_braille["t"] = [".0", "00", "0."]
      latin_braille["u"] = ["0.", "..", "00"]
      latin_braille["v"] = ["0.", "0.", "00"]
      latin_braille["w"] = [".0", "00", ".0"]
      latin_braille["x"] = ["00", "..", "00"]
      latin_braille["y"] = ["00", ".0", "00"]
      latin_braille["z"] = ["0.", ".0", "00"]
      latin_braille["!"] = ["..", "00", "0."]
      latin_braille["'"] = ["..", "..", "0."]
      latin_braille[","] = ["..", "0.", ".."]
      latin_braille["-"] = ["..", "..", "00"]
      latin_braille["."] = ["..", "00", ".0"]
      latin_braille["?"] = ["..", "0.", "00"]
      latin_braille[" "] = ["..", "..", ".."]
      latin_braille["A"] = ["..0.", "....", ".0.."]
      latin_braille["B"] = ["..0.", "..0.", ".0.."]
      latin_braille["C"] = ["..00", "....", ".0.."]
      latin_braille["D"] = ["..00", "...0", ".0.."]
      latin_braille["E"] = ["..0.", "...0", ".0.."]
      latin_braille["F"] = ["..00", "..0.", ".0.."]
      latin_braille["G"] = ["..00", "..00", ".0.."]
      latin_braille["H"] = ["..0.", "..00", ".0.."]
      latin_braille["I"] = ["...0", "..0.", ".0.."]
      latin_braille["J"] = ["...0", "..00", ".0.."]
      latin_braille["K"] = ["..0.", "....", ".00."]
      latin_braille["L"] = ["..0.", "..0.", ".00."]
      latin_braille["M"] = ["..00", "....", ".00."]
      latin_braille["N"] = ["..00", "...0", ".00."]
      latin_braille["O"] = ["..0.", "...0", ".00."]
      latin_braille["P"] = ["..00", "..0.", ".00."]
      latin_braille["Q"] = ["..00", "..00", ".00."]
      latin_braille["R"] = ["..0.", "..00", ".00."]
      latin_braille["S"] = ["...0", "..0.", ".00."]
      latin_braille["T"] = ["...0", "..00", ".00."]
      latin_braille["U"] = ["..0.", "....", ".000"]
      latin_braille["V"] = ["..0.", "..0.", ".000"]
      latin_braille["W"] = ["...0", "..00", ".0.0"]
      latin_braille["X"] = ["..00", "....", ".000"]
      latin_braille["Y"] = ["..00", "...0", ".000"]
      latin_braille["Z"] = ["..0.", "...0", ".000"]
      latin_braille["0"] = [".0.0",".000","00.."]
      latin_braille["1"] = [".00.",".0..","00.."]
      latin_braille["2"] = [".00.",".00.","00.."]
      latin_braille["3"] = [".000",".0..","00.."]
      latin_braille["4"] = [".000",".0.0","00.."]
      latin_braille["5"] = [".00.",".0.0","00.."]
      latin_braille["6"] = [".000",".00.","00.."]
      latin_braille["7"] = [".000",".000","00.."]
      latin_braille["8"] = [".00.",".000","00.."]
      latin_braille["9"] = [".0.0",".00.","00.."]

    @braille_latin = Hash.new
      braille_latin["0....."] = "a"
      braille_latin["0.0..."] = "b"
      braille_latin["00...."] = "c"
      braille_latin["00.0.."] = "d"
      braille_latin["0..0.."] = "e"
      braille_latin["000..."] = "f"
      braille_latin["0000.."] = "g"
      braille_latin["0.00.."] = "h"
      braille_latin[".00..."] = "i"
      braille_latin[".000.."] = "j"
      braille_latin["0...0."] = "k"
      braille_latin["0.0.0."] = "l"
      braille_latin["00..0."] = "m"
      braille_latin["00.00."] = "n"
      braille_latin["0..00."] = "o"
      braille_latin["000.0."] = "p"
      braille_latin["00000."] = "q"
      braille_latin["0.000."] = "r"
      braille_latin[".00.0."] = "s"
      braille_latin[".0000."] = "t"
      braille_latin["0...00"] = "u"
      braille_latin["0.0.00"] = "v"
      braille_latin[".000.0"] = "w"
      braille_latin["00..00"] = "x"
      braille_latin["00.000"] = "y"
      braille_latin["0..000"] = "z"
      braille_latin["......"] = " "
      braille_latin["..000."] = "!"
      braille_latin["....0."] = "'"
      braille_latin["..0..."] = ","
      braille_latin["....00"] = "-"
      braille_latin["..00.0"] = "."
      braille_latin["..0.00"] = "?"
      braille_latin[".....00....."] = "A"
      braille_latin[".....00.0..."] = "B"
      braille_latin[".....000...."] = "C"
      braille_latin[".....000.0.."] = "D"
      braille_latin[".....00..0.."] = "E"
      braille_latin[".....0000..."] = "F"
      braille_latin[".....00000.."] = "G"
      braille_latin[".....00.00.."] = "H"
      braille_latin[".....0.00..."] = "I"
      braille_latin[".....0.000.."] = "J"
      braille_latin[".....00...0."] = "K"
      braille_latin[".....00.0.0."] = "L"
      braille_latin[".....000..0."] = "M"
      braille_latin[".....000.00."] = "N"
      braille_latin[".....00..00."] = "O"
      braille_latin[".....0000.0."] = "P"
      braille_latin[".....000000."] = "Q"
      braille_latin[".....00.000."] = "R"
      braille_latin[".....0.00.0."] = "S"
      braille_latin[".....0.0000."] = "T"
      braille_latin[".....00...00"] = "U"
      braille_latin[".....00.0.00"] = "V"
      braille_latin[".....0.000.0"] = "W"
      braille_latin[".....000..00"] = "X"
      braille_latin[".....000.000"] = "Y"
      braille_latin[".....00..000"] = "Z"
      braille_latin[".0.000.000.."] = "0"
      braille_latin[".0.0000....."] = "1"
      braille_latin[".0.0000.0..."] = "2"
      braille_latin[".0.00000...."] = "3"
      braille_latin[".0.00000.0.."] = "4"
      braille_latin[".0.0000..0.."] = "5"
      braille_latin[".0.000000..."] = "6"
      braille_latin[".0.0000000.."] = "7"
      braille_latin[".0.0000.00.."] = "8"
      braille_latin[".0.000.00..."] = "9"
  end
end
